name: Run checks

on:
  pull_request:
    branches: main
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']

jobs:
  typecheck:
    uses: ./.github/workflows/run-check.yaml
    with:
      command: bun typecheck
  lint:
    uses: ./.github/workflows/run-check.yaml
    with:
      command: bun lint
  lint-markdown:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://avtodev/markdown-lint:v1
        with:
          config: '.markdownlint.json'
          args: '.'
  test:
    uses: ./.github/workflows/run-check.yaml
    with:
      command: bun test
